### ISSUE TITLE
water withdraw data

### ISSUE THREAD

**Issue by landsat12** [usgs/waterdataui#375]
Dear colleague,
 I want to know if there is a water use data or withdraw data that the time step is 1 year for state level in USA.
Thank you very much for your help!
Best,

**Comment by jkreft-usgs** [comment]
The place to access water use data from the UGSS is [here](https://waterdata.usgs.gov/nwis/wu), which gives data through 2015.

**Comment by landsat12** [comment]
Thank you very much! And Do we have a water use time series data with a 1-year time step?
